apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ib6l
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qblq-tenant/rhtap-demo-app/hacbs-test-project-ib6l@sha256:2f1f6059daebb17f1dcef847e5407e4b5ca1f42b65a3b95ca773f1fcb246f285
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
